### ISSUE TITLE
Add eplfs to mergerfs options

### ISSUE THREAD

**Issue by ryecoaaron** [OpenMediaVault-Plugin-Developers/openmediavault-unionfilesystems#12]
Add Existing path, least free space (eplfs) option that was added by newer version of mergerfs.

**Comment by rkrug** [comment]
Would be nice to have it to fill existing drives after migration to mergerfs

**Comment by ryecoaaron** [comment]
And how would you suggest doing that?  That could take a long time as well.

**Comment by rkrug** [comment]
Sorry - I don't understand your question. I just wanted to say that I would like to have this (eplfs) as well.

**Comment by rkrug** [comment]
I just saw it is in the newest versions for OMV 3 - but not 2.2.

**Comment by ryecoaaron** [comment]
I doubt eplfs will be backported to OMV 2.x.  OMV 3.x will be released soon enough.

I was asking how existing drives would be filled after switching to mergerfs.  Sounds like you wanted the drives balanced to have equal amounts after switching?  New writes will obviously do that but existing data won't be balanced.

**Comment by rkrug** [comment]
Backport: fine with me. When is 3.x expected?

Yes - I was only referring to new writes. The rest one can do manually. 

Thanks.
