### ISSUE TITLE
Label/UUID issue with mergerfs in omv 3.x

### ISSUE THREAD

**Issue by Nibb31** [OpenMediaVault-Plugin-Developers/openmediavault-unionfilesystems#18]
I'm having the following problem when creating a mergerfs FS  with OMV3. I'm running OMV 3 on Proxmox with the 4 SATA drives in passthrough mode and SnapRAID:
DATA1
DATA2
DATA3
PARITY (snapraid parity drive)
STORAGE (mergerfs of DATA1, DATA2, DATA3)

After creating the mergerfs in OMV 3, the Filesystems table displays the new FS as "Device: false" and "Label: STORAGE". In OMV 2, the exact same setup displays Device as "Device: media/_uuid_.

When creating a share, or anywhere else in the UI where the drive labels are listed, the mergerfs is listed as media/_uuid_ instead of STORAGE. When selected, the fs is displayed as just "_uuid_".

See thread:
http://forums.openmediavault.org/index.php/Thread/14788-Device-lists-displays-media-uuid-instead-of-mergerfs-filesystem-label/

**Comment by PXIII** [comment]
Hi,

Thanks for this plugin.
Having the same issue:

While creating a pool (repeated several times), for some unknown reason, a given name (like "POOL") was replaced by "/media/2fe90cb3-a2c4-45d1-83cd-a6ce90421e87​" kind. The pool itself is working, but that name makes it confusing when creating shared folders. It would be nice to fix that or to have a workaround.

**Comment by nohatssir** [comment]
Thanks for the report. I know about the problem but I've been focusing on rewriting the whole plugin into a mergerfs plugin that takes a little different approach under the hood. So I won't personally have any fix to this issue and I also have no ETA on the new plugin. If somebody issues a pull request I'll be willing to look it over. :)

**Comment by nohatssir** [comment]
This is fixed with 0a0fca17b954e0866c18037e74316f80fd154f76.
