### ISSUE TITLE
mergerfs shares not working with SMB/FTP/NFS

### ISSUE THREAD

**Issue by Nibb31** [OpenMediaVault-Plugin-Developers/openmediavault-unionfilesystems#20]
I don't know if this is linked to the UUID bug, but mergerfs shares created on OMV 3 are not accessible over SMB/CIFS or FTP or NFS.

To reproduce:
- Create a mergerfs FS
- Create shares to point to mergerfs with R/W user permissions
- Set up SMB or FTP and add shares.
- Try to log in => SMB: Permission denied, FTP: shares are invisible.
- Edit shares to point to individual disks, Save, Apply
- Try to log  => SMB and FTP OK !
- Edit shares to point mergerfs again, Save, Apply
- Try to log in => SMB: Permission denied, FTP: shares are invisible.

**Comment by ryecoaaron** [comment]
The plugin is supposed to put defaults, allow_other in the options field but there seems to be a bug that doesn't add this unless you change the pool type.  Or mybe you deleted the options.   If you don't have allow_other, no one other than root can access the pool.  So, your steps make sense if you are missing allow_other.

**Comment by Nibb31** [comment]
This is fixed in the latest version of the plugin.
