### ISSUE TITLE
Drives cannot be used by multiple pools

### ISSUE THREAD

**Issue by andocromn** [OpenMediaVault-Plugin-Developers/openmediavault-unionfilesystems#21]
When creating a Union Filesystem in the plugin, you are only presented with drives that are not already a part of another Union filesystem.  This does not seem to be a limitation of MergerFS, but rather just a limitation of the plugin.  I have tested creating multiple Union filesystems manually with MergerFS and had no problems.

I am currently doing this using the AuFS / pooling plugin in openmedivault version 2 and need a new solution going forward

**Comment by ryecoaaron** [comment]
This was fixed in the last couple of releases.
