### ISSUE TITLE
custom mount point

### ISSUE THREAD

**Issue by z-vap** [OpenMediaVault-Plugin-Developers/openmediavault-unionfilesystems#22]
Is there a way to have the plugin use a custom mount point instead of the guid generated one?  If not can we have that as an option?  and if blank it can act as it does....  thank you

**Comment by ryecoaaron** [comment]
No to both.  You can install the symlink plugin and create a symlink to /media/LONG_UUID.

**Comment by z-vap** [comment]
ah, did not know there was a symlink plugin. tks
