### ISSUE TITLE
Mounting unionfilesystem fails.

### ISSUE THREAD

**Issue by virtaj** [OpenMediaVault-Plugin-Developers/openmediavault-unionfilesystems#29]
Trying omv 5.0.4-1 and unionfilesystem 5.0.

Creating unionfs through webui works ok and it creates correct entries to fstab. However mounting it fails. Unmount and mount again from terminal works.
`
root@nas:~# cat /etc/fstab
 #>>> [openmediavault]
/dev/disk/by-label/4GBtest              /srv/dev-disk-by-label-4GBtest  ext4    defaults,nofail,user_xattr,noexec,usrjquota=aquota.user,grpjquota=aquota.group,jqfmt=vfsv0,acl  0 2
/dev/disk/by-label/16GT_Verbatim                /srv/dev-disk-by-label-16GT_Verbatim    ext4    defaults,nofail,user_xattr,noexec,usrjquota=aquota.user,grpjquota=aquota.group,jqfmt=vfsv0,acl0 2
/srv/dev-disk-by-label-16GT_Verbatim:/srv/dev-disk-by-label-4GBtest             /srv/1f6d9075-8f35-40bb-aea7-04bc921831c1       fuse.mergerfs   defaults,allow_other,direct_io,use_ino,category.create=epmfs,minfreespace=1G   0 0
'# <<< [openmediavault]

root@nas:~# ls -la /srv/
d?????????  ? ?    ?          ?            ?  1f6d9075-8f35-40bb-aea7-04bc921831c1
drwxr-sr-x  3 root users   4096 Aug 11 18:49  dev-disk-by-label-16GT_Verbatim
drwxr-sr-x  3 root users   4096 Aug 11 17:16  dev-disk-by-label-4GBtest

root@nas:/srv# umount 1f6d9075-8f35-40bb-aea7-04bc921831c1
root@nas:/srv# mount 1f6d9075-8f35-40bb-aea7-04bc921831c1
root@nas:/srv# ls -la
drwxr-sr-x  3 root users   4096 Aug 11 18:49  1f6d9075-8f35-40bb-aea7-04bc921831c1
drwxr-sr-x  3 root users   4096 Aug 11 18:49  dev-disk-by-label-16GT_Verbatim
drwxr-sr-x  3 root users   4096 Aug 11 17:16  dev-disk-by-label-4GBtest
'

**Comment by ryecoaaron** [comment]
All I can think is that it is trying to mount the mountpoint before the directory is created.  I will have to look into it.

**Comment by andocromn** [comment]
I know doesn't help... But I reboot after making changes

The saving grace about mergerfs is that it's path based, so it doesn't care if you unmount and remove a drive.  Point is you don't have to modify Union fs to remove an external drive, though omv won't be happy until you reattach it

**Comment by ryecoaaron** [comment]
Rebooting does work but that wasn't necessary when creating new pools on OMV 4.x.  So, something has changed that I would like to fix.

**Comment by jelofsson** [comment]
I'm experiencing similar problems, rebooting mounts the mountpoint again until I apply any new changes in the OMV then the mountpoint gets inaccessible yet again and I some errors because it cant access the mount.

**Comment by ryecoaaron** [comment]
Are you rebooting before you apply the changes?  If so, reboot after you apply the changes.  The initial problem in this issue is fixed in newer OMV 5.x versions.  Changing the pool options without a reboot will not be "fixed".
