### ISSUE TITLE
Failed to execute command

### ISSUE THREAD

**Issue by jelofsson** [OpenMediaVault-Plugin-Developers/openmediavault-unionfilesystems#30]
```
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; df -PT '/srv/8c478aac-80e6-4ae8-b139-45e7c5bf23ae' 2>&1' with exit code '1': df: /srv/8c478aac-80e6-4ae8-b139-45e7c5bf23ae: No such file or directory
```

I get this message on the File systems tab after activating unionfilesystems and selecting two branches.

**Comment by ryecoaaron** [comment]
On what version of OMV?

**Comment by jelofsson** [comment]
Oh just realized I'm running OMV  4.19.0-5-amd64 and I probably have the unionfilesystems 5. Thats probably the issue right?

**Comment by ryecoaaron** [comment]
This issue has been fixed in OMV 5.x.  You need to update your system in the updates tab.
