### ISSUE TITLE
Attempting to install: Failed to execute command OMV 5.0.8 Union 5

### ISSUE THREAD

**Issue by Galapagon** [OpenMediaVault-Plugin-Developers/openmediavault-unionfilesystems#31]
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  mergerfs
The following NEW packages will be installed:
  mergerfs openmediavault-unionfilesystems
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 227 kB of archives.
After this operation, 774 kB of additional disk space will be used.
Err:1 https://dl.bintray.com/openmediavault-plugin-developers/usul buster/main amd64 mergerfs amd64 2.28.1~debian-buster
  Temporary failure resolving 'dl.bintray.com'
Err:2 https://dl.bintray.com/openmediavault-plugin-developers/usul buster/main amd64 openmediavault-unionfilesystems all 5.0
  Temporary failure resolving 'dl.bintray.com'

>>> *************** Error ***************
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export DEBIAN_FRONTEND=noninteractive; apt-get --yes --allow-downgrades --allow-change-held-packages --fix-missing --allow-unauthenticated --reinstall install openmediavault-unionfilesystems 2>&1' with exit code '100': Reading package lists...

Building dependency tree...

Reading state information...

The following additional packages will be installed:
  mergerfs
The following NEW packages will be installed:
  mergerfs openmediavault-unionfilesystems
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 227 kB of archives.
After this operation, 774 kB of additional disk space will be used.
Err:1 https://dl.bintray.com/openmediavault-plugin-developers/usul buster/main amd64 mergerfs amd64 2.28.1~debian-buster
  Temporary failure resolving 'dl.bintray.com'
Err:2 https://dl.bintray.com/openmediavault-plugin-developers/usul buster/main amd64 openmediavault-unionfilesystems all 5.0
  Temporary failure resolving 'dl.bintray.com'
Unable to correct missing packages.
E
: Failed to fetch https://dl.bintray.com/openmediavault-plugin-developers/usul/pool/main/m/mergerfs/mergerfs_2.28.1.debian-buster_amd64.deb  Temporary failure resolving 'dl.bintray.com'
E: Failed to fetch https://dl.bintray.com/openmediavault-plugin-developers/usul/pool/main/o/openmediavault-unionfilesystems/openmediavault-unionfilesystems_5.0_all.deb  Temporary failure resolving 'dl.bintray.com'
E: Aborting install.
<<< *************************************

>>> *************** Error ***************
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export DEBIAN_FRONTEND=noninteractive; apt-get --yes --allow-downgrades --allow-change-held-packages --fix-missing --allow-unauthenticated --reinstall install openmediavault-unionfilesystems 2>&1' with exit code '100': Reading package lists...

Building dependency tree...

Reading state information...

The following additional packages will be installed:
  mergerfs
The following NEW packages will be installed:
  mergerfs openmediavault-unionfilesystems
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 227 kB of archives.
After this operation, 774 kB of additional disk space will be used.
Err:1 https://dl.bintray.com/openmediavault-plugin-developers/usul buster/main amd64 mergerfs amd64 2.28.1~debian-buster
  Temporary failure resolving 'dl.bintray.com'
Err:2 https://dl.bintray.com/openmediavault-plugin-developers/usul buster/main amd64 openmediavault-unionfilesystems all 5.0
  Temporary failure resolving 'dl.bintray.com'
Unable to correct missing packages.
E
: Failed to fetch https://dl.bintray.com/openmediavault-plugin-developers/usul/pool/main/m/mergerfs/mergerfs_2.28.1.debian-buster_amd64.deb  Temporary failure resolving 'dl.bintray.com'
E: Failed to fetch https://dl.bintray.com/openmediavault-plugin-developers/usul/pool/main/o/openmediavault-unionfilesystems/openmediavault-unionfilesystems_5.0_all.deb  Temporary failure resolving 'dl.bintray.com'
E: Aborting install.
<<< *************************************

>>> *************** Error ***************
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export DEBIAN_FRONTEND=noninteractive; apt-get --yes --allow-downgrades --allow-change-held-packages --fix-missing --allow-unauthenticated --reinstall install openmediavault-unionfilesystems 2>&1' with exit code '100': Reading package lists...

Building dependency tree...

Reading state information...

The following additional packages will be installed:
  mergerfs
The following NEW packages will be installed:
  mergerfs openmediavault-unionfilesystems
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 227 kB of archives.
After this operation, 774 kB of additional disk space will be used.
Err:1 https://dl.bintray.com/openmediavault-plugin-developers/usul buster/main amd64 mergerfs amd64 2.28.1~debian-buster
  Temporary failure resolving 'dl.bintray.com'
Err:2 https://dl.bintray.com/openmediavault-plugin-developers/usul buster/main amd64 openmediavault-unionfilesystems all 5.0
  Temporary failure resolving 'dl.bintray.com'
Unable to correct missing packages.
E
: Failed to fetch https://dl.bintray.com/openmediavault-plugin-developers/usul/pool/main/m/mergerfs/mergerfs_2.28.1.debian-buster_amd64.deb  Temporary failure resolving 'dl.bintray.com'
E: Failed to fetch https://dl.bintray.com/openmediavault-plugin-developers/usul/pool/main/o/openmediavault-unionfilesystems/openmediavault-unionfilesystems_5.0_all.deb  Temporary failure resolving 'dl.bintray.com'
E: Aborting install.
<<< *************************************

>>> *************** Error ***************
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export DEBIAN_FRONTEND=noninteractive; apt-get --yes --allow-downgrades --allow-change-held-packages --fix-missing --allow-unauthenticated --reinstall install openmediavault-unionfilesystems 2>&1' with exit code '100': Reading package lists...

Building dependency tree...

Reading state information...

The following additional packages will be installed:
  mergerfs
The following NEW packages will be installed:
  mergerfs openmediavault-unionfilesystems
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 227 kB of archives.
After this operation, 774 kB of additional disk space will be used.
Err:1 https://dl.bintray.com/openmediavault-plugin-developers/usul buster/main amd64 mergerfs amd64 2.28.1~debian-buster
  Temporary failure resolving 'dl.bintray.com'
Err:2 https://dl.bintray.com/openmediavault-plugin-developers/usul buster/main amd64 openmediavault-unionfilesystems all 5.0
  Temporary failure resolving 'dl.bintray.com'
Unable to correct missing packages.
E
: Failed to fetch https://dl.bintray.com/openmediavault-plugin-developers/usul/pool/main/m/mergerfs/mergerfs_2.28.1.debian-buster_amd64.deb  Temporary failure resolving 'dl.bintray.com'
E: Failed to fetch https://dl.bintray.com/openmediavault-plugin-developers/usul/pool/main/o/openmediavault-unionfilesystems/openmediavault-unionfilesystems_5.0_all.deb  Temporary failure resolving 'dl.bintray.com'
E: Aborting install.
<<< *************************************

>>> *************** Error ***************
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export DEBIAN_FRONTEND=noninteractive; apt-get --yes --allow-downgrades --allow-change-held-packages --fix-missing --allow-unauthenticated --reinstall install openmediavault-unionfilesystems 2>&1' with exit code '100': Reading package lists...

Building dependency tree...

Reading state information...

The following additional packages will be installed:
  mergerfs
The following NEW packages will be installed:
  mergerfs openmediavault-unionfilesystems
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 227 kB of archives.
After this operation, 774 kB of additional disk space will be used.
Err:1 https://dl.bintray.com/openmediavault-plugin-developers/usul buster/main amd64 mergerfs amd64 2.28.1~debian-buster
  Temporary failure resolving 'dl.bintray.com'
Err:2 https://dl.bintray.com/openmediavault-plugin-developers/usul buster/main amd64 openmediavault-unionfilesystems all 5.0
  Temporary failure resolving 'dl.bintray.com'
Unable to correct missing packages.
E
: Failed to fetch https://dl.bintray.com/openmediavault-plugin-developers/usul/pool/main/m/mergerfs/mergerfs_2.28.1.debian-buster_amd64.deb  Temporary failure resolving 'dl.bintray.com'
E: Failed to fetch https://dl.bintray.com/openmediavault-plugin-developers/usul/pool/main/o/openmediavault-unionfilesystems/openmediavault-unionfilesystems_5.0_all.deb  Temporary failure resolving 'dl.bintray.com'
E: Aborting install.
<<< *************************************

>>> *************** Error ***************
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export DEBIAN_FRONTEND=noninteractive; apt-get --yes --allow-downgrades --allow-change-held-packages --fix-missing --allow-unauthenticated --reinstall install openmediavault-unionfilesystems 2>&1' with exit code '100': Reading package lists...

Building dependency tree...

Reading state information...

The following additional packages will be installed:
  mergerfs
The following NEW packages will be installed:
  mergerfs openmediavault-unionfilesystems
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 227 kB of archives.
After this operation, 774 kB of additional disk space will be used.
Err:1 https://dl.bintray.com/openmediavault-plugin-developers/usul buster/main amd64 mergerfs amd64 2.28.1~debian-buster
  Temporary failure resolving 'dl.bintray.com'
Err:2 https://dl.bintray.com/openmediavault-plugin-developers/usul buster/main amd64 openmediavault-unionfilesystems all 5.0
  Temporary failure resolving 'dl.bintray.com'
Unable to correct missing packages.
E
: Failed to fetch https://dl.bintray.com/openmediavault-plugin-developers/usul/pool/main/m/mergerfs/mergerfs_2.28.1.debian-buster_amd64.deb  Temporary failure resolving 'dl.bintray.com'
E: Failed to fetch https://dl.bintray.com/openmediavault-plugin-developers/usul/pool/main/o/openmediavault-unionfilesystems/openmediavault-unionfilesystems_5.0_all.deb  Temporary failure resolving 'dl.bintray.com'
E: Aborting install.
<<< *************************************

>>> *************** Error ***************
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export DEBIAN_FRONTEND=noninteractive; apt-get --yes --allow-downgrades --allow-change-held-packages --fix-missing --allow-unauthenticated --reinstall install openmediavault-unionfilesystems 2>&1' with exit code '100': Reading package lists...

Building dependency tree...

Reading state information...

The following additional packages will be installed:
  mergerfs
The following NEW packages will be installed:
  mergerfs openmediavault-unionfilesystems
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 227 kB of archives.
After this operation, 774 kB of additional disk space will be used.
Err:1 https://dl.bintray.com/openmediavault-plugin-developers/usul buster/main amd64 mergerfs amd64 2.28.1~debian-buster
  Temporary failure resolving 'dl.bintray.com'
Err:2 https://dl.bintray.com/openmediavault-plugin-developers/usul buster/main amd64 openmediavault-unionfilesystems all 5.0
  Temporary failure resolving 'dl.bintray.com'
Unable to correct missing packages.
E
: Failed to fetch https://dl.bintray.com/openmediavault-plugin-developers/usul/pool/main/m/mergerfs/mergerfs_2.28.1.debian-buster_amd64.deb  Temporary failure resolving 'dl.bintray.com'
E: Failed to fetch https://dl.bintray.com/openmediavault-plugin-developers/usul/pool/main/o/openmediavault-unionfilesystems/openmediavault-unionfilesystems_5.0_all.deb  Temporary failure resolving 'dl.bintray.com'
E: Aborting install.
<<< *************************************

>>> *************** Error ***************
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export DEBIAN_FRONTEND=noninteractive; apt-get --yes --allow-downgrades --allow-change-held-packages --fix-missing --allow-unauthenticated --reinstall install openmediavault-unionfilesystems 2>&1' with exit code '100': Reading package lists...

Building dependency tree...

Reading state information...

The following additional packages will be installed:
  mergerfs
The following NEW packages will be installed:
  mergerfs openmediavault-unionfilesystems
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 227 kB of archives.
After this operation, 774 kB of additional disk space will be used.
Err:1 https://dl.bintray.com/openmediavault-plugin-developers/usul buster/main amd64 mergerfs amd64 2.28.1~debian-buster
  Temporary failure resolving 'dl.bintray.com'
Err:2 https://dl.bintray.com/openmediavault-plugin-developers/usul buster/main amd64 openmediavault-unionfilesystems all 5.0
  Temporary failure resolving 'dl.bintray.com'
Unable to correct missing packages.
E
: Failed to fetch https://dl.bintray.com/openmediavault-plugin-developers/usul/pool/main/m/mergerfs/mergerfs_2.28.1.debian-buster_amd64.deb  Temporary failure resolving 'dl.bintray.com'
E: Failed to fetch https://dl.bintray.com/openmediavault-plugin-developers/usul/pool/main/o/openmediavault-unionfilesystems/openmediavault-unionfilesystems_5.0_all.deb  Temporary failure resolving 'dl.bintray.com'
E: Aborting install.
<<< *************************************

>>> *************** Error ***************
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export DEBIAN_FRONTEND=noninteractive; apt-get --yes --allow-downgrades --allow-change-held-packages --fix-missing --allow-unauthenticated --reinstall install openmediavault-unionfilesystems 2>&1' with exit code '100': Reading package lists...

Building dependency tree...

Reading state information...

The following additional packages will be installed:
  mergerfs
The following NEW packages will be installed:
  mergerfs openmediavault-unionfilesystems
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 227 kB of archives.
After this operation, 774 kB of additional disk space will be used.
Err:1 https://dl.bintray.com/openmediavault-plugin-developers/usul buster/main amd64 mergerfs amd64 2.28.1~debian-buster
  Temporary failure resolving 'dl.bintray.com'
Err:2 https://dl.bintray.com/openmediavault-plugin-developers/usul buster/main amd64 openmediavault-unionfilesystems all 5.0
  Temporary failure resolving 'dl.bintray.com'
Unable to correct missing packages.
E
: Failed to fetch https://dl.bintray.com/openmediavault-plugin-developers/usul/pool/main/m/mergerfs/mergerfs_2.28.1.debian-buster_amd64.deb  Temporary failure resolving 'dl.bintray.com'
E: Failed to fetch https://dl.bintray.com/openmediavault-plugin-developers/usul/pool/main/o/openmediavault-unionfilesystems/openmediavault-unionfilesystems_5.0_all.deb  Temporary failure resolving 'dl.bintray.com'
E: Aborting install.
<<< *************************************

>>> *************** Error ***************
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export DEBIAN_FRONTEND=noninteractive; apt-get --yes --allow-downgrades --allow-change-held-packages --fix-missing --allow-unauthenticated --reinstall install openmediavault-unionfilesystems 2>&1' with exit code '100': Reading package lists...

Building dependency tree...

Reading state information...

The following additional packages will be installed:
  mergerfs
The following NEW packages will be installed:
  mergerfs openmediavault-unionfilesystems
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 227 kB of archives.
After this operation, 774 kB of additional disk space will be used.
Err:1 https://dl.bintray.com/openmediavault-plugin-developers/usul buster/main amd64 mergerfs amd64 2.28.1~debian-buster
  Temporary failure resolving 'dl.bintray.com'
Err:2 https://dl.bintray.com/openmediavault-plugin-developers/usul buster/main amd64 openmediavault-unionfilesystems all 5.0
  Temporary failure resolving 'dl.bintray.com'
Unable to correct missing packages.
E
: Failed to fetch https://dl.bintray.com/openmediavault-plugin-developers/usul/pool/main/m/mergerfs/mergerfs_2.28.1.debian-buster_amd64.deb  Temporary failure resolving 'dl.bintray.com'
E: Failed to fetch https://dl.bintray.com/openmediavault-plugin-developers/usul/pool/main/o/openmediavault-unionfilesystems/openmediavault-unionfilesystems_5.0_all.deb  Temporary failure resolving 'dl.bintray.com'
E: Aborting install.
<<< *************************************

>>> *************** Error ***************
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export DEBIAN_FRONTEND=noninteractive; apt-get --yes --allow-downgrades --allow-change-held-packages --fix-missing --allow-unauthenticated --reinstall install openmediavault-unionfilesystems 2>&1' with exit code '100': Reading package lists...

Building dependency tree...

Reading state information...

The following additional packages will be installed:
  mergerfs
The following NEW packages will be installed:
  mergerfs openmediavault-unionfilesystems
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 227 kB of archives.
After this operation, 774 kB of additional disk space will be used.
Err:1 https://dl.bintray.com/openmediavault-plugin-developers/usul buster/main amd64 mergerfs amd64 2.28.1~debian-buster
  Temporary failure resolving 'dl.bintray.com'
Err:2 https://dl.bintray.com/openmediavault-plugin-developers/usul buster/main amd64 openmediavault-unionfilesystems all 5.0
  Temporary failure resolving 'dl.bintray.com'
Unable to correct missing packages.
E
: Failed to fetch https://dl.bintray.com/openmediavault-plugin-developers/usul/pool/main/m/mergerfs/mergerfs_2.28.1.debian-buster_amd64.deb  Temporary failure resolving 'dl.bintray.com'
E: Failed to fetch https://dl.bintray.com/openmediavault-plugin-developers/usul/pool/main/o/openmediavault-unionfilesystems/openmediavault-unionfilesystems_5.0_all.deb  Temporary failure resolving 'dl.bintray.com'
E: Aborting install.
<<< *************************************

>>> *************** Error ***************
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export DEBIAN_FRONTEND=noninteractive; apt-get --yes --allow-downgrades --allow-change-held-packages --fix-missing --allow-unauthenticated --reinstall install openmediavault-unionfilesystems 2>&1' with exit code '100': Reading package lists...

Building dependency tree...

Reading state information...

The following additional packages will be installed:
  mergerfs
The following NEW packages will be installed:
  mergerfs openmediavault-unionfilesystems
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 227 kB of archives.
After this operation, 774 kB of additional disk space will be used.
Err:1 https://dl.bintray.com/openmediavault-plugin-developers/usul buster/main amd64 mergerfs amd64 2.28.1~debian-buster
  Temporary failure resolving 'dl.bintray.com'
Err:2 https://dl.bintray.com/openmediavault-plugin-developers/usul buster/main amd64 openmediavault-unionfilesystems all 5.0
  Temporary failure resolving 'dl.bintray.com'
Unable to correct missing packages.
E
: Failed to fetch https://dl.bintray.com/openmediavault-plugin-developers/usul/pool/main/m/mergerfs/mergerfs_2.28.1.debian-buster_amd64.deb  Temporary failure resolving 'dl.bintray.com'
E: Failed to fetch https://dl.bintray.com/openmediavault-plugin-developers/usul/pool/main/o/openmediavault-unionfilesystems/openmediavault-unionfilesystems_5.0_all.deb  Temporary failure resolving 'dl.bintray.com'
E: Aborting install.
<<< *************************************

>>> *************** Error ***************
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export DEBIAN_FRONTEND=noninteractive; apt-get --yes --allow-downgrades --allow-change-held-packages --fix-missing --allow-unauthenticated --reinstall install openmediavault-unionfilesystems 2>&1' with exit code '100': Reading package lists...

Building dependency tree...

Reading state information...

The following additional packages will be installed:
  mergerfs
The following NEW packages will be installed:
  mergerfs openmediavault-unionfilesystems
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 227 kB of archives.
After this operation, 774 kB of additional disk space will be used.
Err:1 https://dl.bintray.com/openmediavault-plugin-developers/usul buster/main amd64 mergerfs amd64 2.28.1~debian-buster
  Temporary failure resolving 'dl.bintray.com'
Err:2 https://dl.bintray.com/openmediavault-plugin-developers/usul buster/main amd64 openmediavault-unionfilesystems all 5.0
  Temporary failure resolving 'dl.bintray.com'
Unable to correct missing packages.
E
: Failed to fetch https://dl.bintray.com/openmediavault-plugin-developers/usul/pool/main/m/mergerfs/mergerfs_2.28.1.debian-buster_amd64.deb  Temporary failure resolving 'dl.bintray.com'
E: Failed to fetch https://dl.bintray.com/openmediavault-plugin-developers/usul/pool/main/o/openmediavault-unionfilesystems/openmediavault-unionfilesystems_5.0_all.deb  Temporary failure resolving 'dl.bintray.com'
E: Aborting install.
<<< *************************************

>>> *************** Error ***************
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export DEBIAN_FRONTEND=noninteractive; apt-get --yes --allow-downgrades --allow-change-held-packages --fix-missing --allow-unauthenticated --reinstall install openmediavault-unionfilesystems 2>&1' with exit code '100': Reading package lists...

Building dependency tree...

Reading state information...

The following additional packages will be installed:
  mergerfs
The following NEW packages will be installed:
  mergerfs openmediavault-unionfilesystems
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 227 kB of archives.
After this operation, 774 kB of additional disk space will be used.
Err:1 https://dl.bintray.com/openmediavault-plugin-developers/usul buster/main amd64 mergerfs amd64 2.28.1~debian-buster
  Temporary failure resolving 'dl.bintray.com'
Err:2 https://dl.bintray.com/openmediavault-plugin-developers/usul buster/main amd64 openmediavault-unionfilesystems all 5.0
  Temporary failure resolving 'dl.bintray.com'
Unable to correct missing packages.
E
: Failed to fetch https://dl.bintray.com/openmediavault-plugin-developers/usul/pool/main/m/mergerfs/mergerfs_2.28.1.debian-buster_amd64.deb  Temporary failure resolving 'dl.bintray.com'
E: Failed to fetch https://dl.bintray.com/openmediavault-plugin-developers/usul/pool/main/o/openmediavault-unionfilesystems/openmediavault-unionfilesystems_5.0_all.deb  Temporary failure resolving 'dl.bintray.com'
E: Aborting install.
<<< *************************************

>>> *************** Error ***************
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export DEBIAN_FRONTEND=noninteractive; apt-get --yes --allow-downgrades --allow-change-held-packages --fix-missing --allow-unauthenticated --reinstall install openmediavault-unionfilesystems 2>&1' with exit code '100': Reading package lists...

Building dependency tree...

Reading state information...

The following additional packages will be installed:
  mergerfs
The following NEW packages will be installed:
  mergerfs openmediavault-unionfilesystems
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 227 kB of archives.
After this operation, 774 kB of additional disk space will be used.
Err:1 https://dl.bintray.com/openmediavault-plugin-developers/usul buster/main amd64 mergerfs amd64 2.28.1~debian-buster
  Temporary failure resolving 'dl.bintray.com'
Err:2 https://dl.bintray.com/openmediavault-plugin-developers/usul buster/main amd64 openmediavault-unionfilesystems all 5.0
  Temporary failure resolving 'dl.bintray.com'
Unable to correct missing packages.
E
: Failed to fetch https://dl.bintray.com/openmediavault-plugin-developers/usul/pool/main/m/mergerfs/mergerfs_2.28.1.debian-buster_amd64.deb  Temporary failure resolving 'dl.bintray.com'
E: Failed to fetch https://dl.bintray.com/openmediavault-plugin-developers/usul/pool/main/o/openmediavault-unionfilesystems/openmediavault-unionfilesystems_5.0_all.deb  Temporary failure resolving 'dl.bintray.com'
E: Aborting install.
<<< *************************************

>>> *************** Error ***************
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export DEBIAN_FRONTEND=noninteractive; apt-get --yes --allow-downgrades --allow-change-held-packages --fix-missing --allow-unauthenticated --reinstall install openmediavault-unionfilesystems 2>&1' with exit code '100': Reading package lists...

Building dependency tree...

Reading state information...

The following additional packages will be installed:
  mergerfs
The following NEW packages will be installed:
  mergerfs openmediavault-unionfilesystems
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 227 kB of archives.
After this operation, 774 kB of additional disk space will be used.
Err:1 https://dl.bintray.com/openmediavault-plugin-developers/usul buster/main amd64 mergerfs amd64 2.28.1~debian-buster
  Temporary failure resolving 'dl.bintray.com'
Err:2 https://dl.bintray.com/openmediavault-plugin-developers/usul buster/main amd64 openmediavault-unionfilesystems all 5.0
  Temporary failure resolving 'dl.bintray.com'
Unable to correct missing packages.
E
: Failed to fetch https://dl.bintray.com/openmediavault-plugin-developers/usul/pool/main/m/mergerfs/mergerfs_2.28.1.debian-buster_amd64.deb  Temporary failure resolving 'dl.bintray.com'
E: Failed to fetch https://dl.bintray.com/openmediavault-plugin-developers/usul/pool/main/o/openmediavault-unionfilesystems/openmediavault-unionfilesystems_5.0_all.deb  Temporary failure resolving 'dl.bintray.com'
E: Aborting install.
<<< *************************************

>>> *************** Error ***************
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export DEBIAN_FRONTEND=noninteractive; apt-get --yes --allow-downgrades --allow-change-held-packages --fix-missing --allow-unauthenticated --reinstall install openmediavault-unionfilesystems 2>&1' with exit code '100': Reading package lists...

Building dependency tree...

Reading state information...

The following additional packages will be installed:
  mergerfs
The following NEW packages will be installed:
  mergerfs openmediavault-unionfilesystems
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 227 kB of archives.
After this operation, 774 kB of additional disk space will be used.
Err:1 https://dl.bintray.com/openmediavault-plugin-developers/usul buster/main amd64 mergerfs amd64 2.28.1~debian-buster
  Temporary failure resolving 'dl.bintray.com'
Err:2 https://dl.bintray.com/openmediavault-plugin-developers/usul buster/main amd64 openmediavault-unionfilesystems all 5.0
  Temporary failure resolving 'dl.bintray.com'
Unable to correct missing packages.
E
: Failed to fetch https://dl.bintray.com/openmediavault-plugin-developers/usul/pool/main/m/mergerfs/mergerfs_2.28.1.debian-buster_amd64.deb  Temporary failure resolving 'dl.bintray.com'
E: Failed to fetch https://dl.bintray.com/openmediavault-plugin-developers/usul/pool/main/o/openmediavault-unionfilesystems/openmediavault-unionfilesystems_5.0_all.deb  Temporary failure resolving 'dl.bintray.com'
E: Aborting install.
<<< *************************************

>>> *************** Error ***************
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export DEBIAN_FRONTEND=noninteractive; apt-get --yes --allow-downgrades --allow-change-held-packages --fix-missing --allow-unauthenticated --reinstall install openmediavault-unionfilesystems 2>&1' with exit code '100': Reading package lists...

Building dependency tree...

Reading state information...

The following additional packages will be installed:
  mergerfs
The following NEW packages will be installed:
  mergerfs openmediavault-unionfilesystems
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 227 kB of archives.
After this operation, 774 kB of additional disk space will be used.
Err:1 https://dl.bintray.com/openmediavault-plugin-developers/usul buster/main amd64 mergerfs amd64 2.28.1~debian-buster
  Temporary failure resolving 'dl.bintray.com'
Err:2 https://dl.bintray.com/openmediavault-plugin-developers/usul buster/main amd64 openmediavault-unionfilesystems all 5.0
  Temporary failure resolving 'dl.bintray.com'
Unable to correct missing packages.
E
: Failed to fetch https://dl.bintray.com/openmediavault-plugin-developers/usul/pool/main/m/mergerfs/mergerfs_2.28.1.debian-buster_amd64.deb  Temporary failure resolving 'dl.bintray.com'
E: Failed to fetch https://dl.bintray.com/openmediavault-plugin-developers/usul/pool/main/o/openmediavault-unionfilesystems/openmediavault-unionfilesystems_5.0_all.deb  Temporary failure resolving 'dl.bintray.com'
E: Aborting install.
<<< *************************************

>>> *************** Error ***************
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export DEBIAN_FRONTEND=noninteractive; apt-get --yes --allow-downgrades --allow-change-held-packages --fix-missing --allow-unauthenticated --reinstall install openmediavault-unionfilesystems 2>&1' with exit code '100': Reading package lists...

Building dependency tree...

Reading state information...

The following additional packages will be installed:
  mergerfs
The following NEW packages will be installed:
  mergerfs openmediavault-unionfilesystems
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 227 kB of archives.
After this operation, 774 kB of additional disk space will be used.
Err:1 https://dl.bintray.com/openmediavault-plugin-developers/usul buster/main amd64 mergerfs amd64 2.28.1~debian-buster
  Temporary failure resolving 'dl.bintray.com'
Err:2 https://dl.bintray.com/openmediavault-plugin-developers/usul buster/main amd64 openmediavault-unionfilesystems all 5.0
  Temporary failure resolving 'dl.bintray.com'
Unable to correct missing packages.
E
: Failed to fetch https://dl.bintray.com/openmediavault-plugin-developers/usul/pool/main/m/mergerfs/mergerfs_2.28.1.debian-buster_amd64.deb  Temporary failure resolving 'dl.bintray.com'
E: Failed to fetch https://dl.bintray.com/openmediavault-plugin-developers/usul/pool/main/o/openmediavault-unionfilesystems/openmediavault-unionfilesystems_5.0_all.deb  Temporary failure resolving 'dl.bintray.com'
E: Aborting install.
<<< *************************************

>>> *************** Error ***************
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export DEBIAN_FRONTEND=noninteractive; apt-get --yes --allow-downgrades --allow-change-held-packages --fix-missing --allow-unauthenticated --reinstall install openmediavault-unionfilesystems 2>&1' with exit code '100': Reading package lists...

Building dependency tree...

Reading state information...

The following additional packages will be installed:
  mergerfs
The following NEW packages will be installed:
  mergerfs openmediavault-unionfilesystems
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 227 kB of archives.
After this operation, 774 kB of additional disk space will be used.
Err:1 https://dl.bintray.com/openmediavault-plugin-developers/usul buster/main amd64 mergerfs amd64 2.28.1~debian-buster
  Temporary failure resolving 'dl.bintray.com'
Err:2 https://dl.bintray.com/openmediavault-plugin-developers/usul buster/main amd64 openmediavault-unionfilesystems all 5.0
  Temporary failure resolving 'dl.bintray.com'
Unable to correct missing packages.
E
: Failed to fetch https://dl.bintray.com/openmediavault-plugin-developers/usul/pool/main/m/mergerfs/mergerfs_2.28.1.debian-buster_amd64.deb  Temporary failure resolving 'dl.bintray.com'
E: Failed to fetch https://dl.bintray.com/openmediavault-plugin-developers/usul/pool/main/o/openmediavault-unionfilesystems/openmediavault-unionfilesystems_5.0_all.deb  Temporary failure resolving 'dl.bintray.com'
E: Aborting install.
<<< *************************************

**Comment by Galapagon** [comment]
I was able to upload Unionfilesystems_5.0 manually, but mergerfs says
"Failed to upload package 'mergerfs_2.28.1.debian-buster_amd64.deb'. The package name does not match the plugin naming convention."

**Comment by Galapagon** [comment]
I was able to get around this by uploading mergerfs to the updates tab

**Comment by ryecoaaron** [comment]
Your first issue was a DNS issue - read problem 6 here - https://forum.openmediavault.org/index.php/Thread/21269-Solutions-to-common-problems/

Your second issue is that mergerfs is not the plugin.  openmediavault-unionfilesystems is the plugin.  mergerfs is a dependency.
