### ISSUE TITLE
mergerfs not honoring MFS policy?

### ISSUE THREAD

**Issue by zeitchef** [OpenMediaVault-Plugin-Developers/openmediavault-unionfilesystems#37]
Hi, I'm not entirely sure this is the right place to create an issue, please let me know if not. The OMV forum is currently down, so I thought I'd give this a try.

I'm building a fresh OMV5 server and using the plugin. I've got 3 disks to pool (4TB, 2TB, 1TB) all freshly-formatted BTRFS. I've set the policy to "Most free space" and left the other defaults when creating the pool. The data on the disks is music files, all highly organized, and is currently being dumped from a previous disk via rsync.

The problem I'm having is that when adding data to the pool, it becomes MUCH smaller than the total storage of the drives (which is 6.7TB). Adding 1TB of data cut the total size of the pool in half (see screenshot). I've checked the individual disks and the existing data paths are being honored... should this be the case?

<img width="1440" alt="Screen Shot 2020-03-14 at 22 26 33" src="https://user-images.githubusercontent.com/6670659/76690756-bdb7c200-6643-11ea-85c8-480fd8b9b3f5.png">

**Comment by ryecoaaron** [comment]
Are you saying 6.37 TiB is less than you were expecting?  You do know that 6.37 TiB = 7.0 TB?  This is just a rounding/data formatting issue.
