### ISSUE TITLE
Creating New Pool on OMV5 Fails

### ISSUE THREAD

**Issue by mike391** [OpenMediaVault-Plugin-Developers/openmediavault-unionfilesystems#39]
When creating a new pool, an error appears:
`: Missing 'required' attribute 'self_mntentref'.`

And the pool is not created.

Seen on a fresh install of OMV5 and openmediavault-unionfilesystems 5.1.2 plugin

**Comment by ryecoaaron** [comment]
Did you clear your browser cache?

**Comment by mike391** [comment]
Oh my god.... I thought I did but I just tried an incognito tab now and it worked...
