### ISSUE TITLE
add MSP (most shared path) based policies to the web ui

### ISSUE THREAD

**Issue by TomW1605** [OpenMediaVault-Plugin-Developers/openmediavault-unionfilesystems#41]
please add the new MSP (most shared path) policies to the web ui
[policies ](https://github.com/trapexit/mergerfs#policy-descriptions)

**Comment by ryecoaaron** [comment]
I would prefer not to have to add features to this plugin since it has been consolidated into openmediavault-mergerfs with OMV 6.x and has those polices - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-mergerfs/blob/main/usr/share/openmediavault/workbench/component.d/omv-storage-mergerfs-form-page.yaml#L87

**Comment by ryecoaaron** [comment]
The release candidate for OMV 6 was released at the beginning November and there have been 14 updates since.

I agree there is no harm but you are the only one asking for it and it takes my time and two plugins need the update and there won't be any translations...

5.1.3 is in the repo.

**Comment by TomW1605** [comment]
ok thanks.

i noticed that you only edited the ui file. from my tests you also need to edit the files in [datamodels](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-unionfilesystems/tree/master/usr/share/openmediavault/datamodels) otherwise it will through an error if you pick the new policies. im happy to make a PR for this if you want

**Comment by ryecoaaron** [comment]
And now it takes even more of my time.  I should've just said use the mergerfsfolders plugin since it already allowed the new policies.  5.1.4 in the repo.

**Comment by TomW1605** [comment]
oh thanks for that. i didnt know about the mergerfsfolders plugin. 

sorry for taking your time
