### ISSUE TITLE
AUFS show no referenced in Filesystem but is used on shared Folders

### ISSUE THREAD

**Issue by raulfg3** [OpenMediaVault-Plugin-Developers/openmediavault-unionfilesystems#6]
I use AUFS to joint 8 Disk, and use AUFS Disk as base for my shared folders.

I notice that this shared Folders are not referenced on Filesystem , see my screen capture  http://bugtracker.openmediavault.org/view.php?id=1340

Bug in OMV, and the answer of Votdev: To fix the issue the OMVFilesystemUnion::getDeviceFile() method must return the correct data.

**Comment by ryecoaaron** [comment]
Commit b4624e45baf98423f93849d55c13da11638c8742 caused this.  Working on a fix.

**Comment by ryecoaaron** [comment]
Fixed in OMV 2.0.11 not the plugin.
